# Generated by Django 5.2 on 2025-04-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='point',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
