# Generated by Django 5.2 on 2025-05-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='paths',
            field=models.JSONField(default=list),
        ),
    ]
