# Generated by Django 5.2 on 2025-05-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_gameboard_paths'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gamestate',
            new_name='paths',
        ),
        migrations.RemoveField(
            model_name='gameboard',
            name='paths',
        ),
    ]
